### ISSUE TITLE
Serialization of `File`/`Image` objects

### ISSUE THREAD

**Issue by Lustmored** [kbond/filesystem#47]
It would be great if `File` objects could be easily serializable out of the box. We could directly benefit from it within live components (where uploaded file would need to be preserved on requests without persisting to entity). It could work in a similar matter to Doctrine type, but probably a bit simpler.

I think `File`/`Image` objects could be serialized to something as simple as a single string "{filesystem}://{path}" and get deserialized as `LazyFile`/`LazyImage`.

At the same time `PendingFile` and any kind of temporary file should throw/fail to serialize as its representation wouldn't exist on deserialization.

This would allow upload file consumers (like planned live component) to simply validate `PendingFile` on upload and upon success write it to dedicated filesystem and store returned object in a serializable context for session/other temporary storage without going another mile here and there to ensure it's an usable object.

**Comment by kbond** [comment]
Interesting, this is a good idea.

With live-components, this was my thought exactly, a `File`/`Image` de/normalizer. The de/normalizer's should probably live in this library and be registered with the bundle by default. WDYT?

Are you thinking they'd be serializable themselves (`__serialize()`/`__unserialize()`) or require a normalizer? I don't believe we can `serialize()` a `File`, then `unserialize()` into a `LazyFile`.

**Comment by kbond** [comment]
I explored this in #51.
