### ISSUE TITLE
Default filesystem in Dependency Injection

### ISSUE THREAD

**Issue by Lustmored** [kbond/filesystem#48]
It looks a bit weird to me that by default `Filesystem` autowires `MultiFilesystem` with all filesystems.

I think if we define `default_filesystem` it could be the default filesystem for autowire too. And `MultiFilesystem` should be only used when type-hinted as `MultiFilesystem`.

**Comment by kbond** [comment]
This is fair - my thinking was the `MultiFilesystem` with a _default_ would act exactly like the default `Filesystem` but yeah, I get it would be unexpected to be able to _sneakily_ get the other filesystems.
