### ISSUE TITLE
`PendingFile::image()` method?

### ISSUE THREAD

**Issue by kbond** [kbond/filesystem#55]
Relates to #52 and #15.

Say we have a Symfony `UploadedFile` object (in your controller) and we want to set this on an entity (using `PendingFile`) but, it's an image file and you want to do some standard manipulations first.

Idea:

```php
$user->profileImage = PendingFile::image($uploadedFile, function(GDImage $image) {
    // manipulate $image

    return $image;
});
```

**Comment by Lustmored** [comment]
That'd surely come in handy - definitely a thing we shall implement one way or the other once we get #52 sorted out :+1:
